# flake8: noqa

from typing import Optional, List


class SMBus():
    def __init__(self, bus: int, force: Optional[bool] = None) -> None: ...

    def write_byte_data(self, i2c_addr: int, register: int, value: int) -> None: ...

    def write_byte(self, i2c_addr: int, value: int) -> None: ...

    def read_byte_data(self, i2c_addr: int, register: int) -> int: ...

    def read_byte(self, i2c_addr: int) -> int: ...

    def read_word_data(self, i2c_addr: int, register: int) -> int: ...

    def write_word_data(self, i2c_addr: int, register: int, value: int) -> None: ...

    def read_i2c_block_data(self, i2c_addr: int, register: int, length: int, force: Optional[bool] = None) -> List[int]: ...

    def write_i2c_block_data(self, i2c_addr: int, register: int, data: List[int]) -> None: ...

    def open(self, bus: int) -> None: ...

    def close(self) -> None: ...
